### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by itimmisriis** [Parrot-Developers/groundsdk-android#2]
I am getting this error several seconds after the application loads:
> 2019-07-12 10:17:34.064 1345-1345/com.parrot.drone.groundsdkdemo E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.parrot.drone.groundsdkdemo, PID: 1345
>     java.lang.NullPointerException: Attempt to read from null array
>         at com.parrot.drone.sdkcore.arsdk.backend.ble.ArsdkBleDiscovery.getDeviceType(ArsdkBleDiscovery.java:330)
>         at com.parrot.drone.sdkcore.arsdk.backend.ble.ArsdkBleDiscovery.access$500(ArsdkBleDiscovery.java:69)
>         at com.parrot.drone.sdkcore.arsdk.backend.ble.ArsdkBleDiscovery$2.onScanResult(ArsdkBleDiscovery.java:214)
>         at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:478)
>         at android.os.Handler.handleCallback(Handler.java:790)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:164)
>         at android.app.ActivityThread.main(ActivityThread.java:6494)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 2019-07-12 10:17:34.064 1345-1345/com.parrot.drone.groundsdkdemo A/arsdk: Stopping pomp loop due to uncaught NullPointerException on Thread[main,5,main]

It originates from this code here:

>     /**
>      * Gets the device type matched by the given scan record.
>      *
>      * @param scanRecord the scan record to retrieve the device type from
>      *
>      * @return the scanned device type
>      */
>     @SuppressLint("WrongConstant")
>     @ArsdkDevice.Type
>     private static int getDeviceType(@NonNull ScanRecord scanRecord) {
>         byte[] manufacturerData = scanRecord.getManufacturerSpecificData(PARROT_MANUFACTURER_ID);
>         assert manufacturerData != null; // we only scan for parrot devices, so this should always match
>         return manufacturerData[3] << 8 | manufacturerData[2];
>     }

Stepping into it, I see that the manufacturerData is coming up as Null.

**Comment by mvinel** [comment]
Fixed in 1.1.0 release
