### ISSUE TITLE
Many Issues building groundskd-android

### ISSUE THREAD

**Issue by fuzzlogdev** [Parrot-Developers/groundsdk-android#5]
Mostly related to using variables inside build.grade within many of the projects while there doesn't seem to be a place where the variables are declared and instantiated.

e.g., sdkcore\build gradle
```
dependencies {
    implementation androidXAnnotations
}
```
androidXAnotiations produces the following error when attempting to build in android studio:

> "Could not get unknown property 'androidXAnnotations'"

A second one also in the same file appears within the body of the "task" section:
```
    ext.srcFiles = file("${arsdkxmldir}/xml").listFiles().findAll {
        it.name.endsWith('.xml')
    }
```
This causes the following error:

> Could not get unknown property 'arsdkxmldir'

Where are these variables declared?  I cannot find them anywhere in the downloaded code.

**Comment by mvinel** [comment]
Hi,

The 'groundsdk-android' git repository is only a part of the whole groundsdk workspace.
To build groundsdk, please follow the instructions [here](https://developer.parrot.com/docs/groundsdk-android/buildgroundsdk.html).

Regards.
