### ISSUE TITLE
ArsdkFeaturesGeneric and ArsdkFeatureCamera nowhere to be found

### ISSUE THREAD

**Issue by fuzzlogdev** [Parrot-Developers/groundsdk-android#6]
Attempting to build groundsdk-android using android studio. After fiddling around, was able to finally get past all the gradle issues. Now attempting to build results in code not compiling due to missing classes.  The ones i'm dealing with right now are:

**ArsdkFeatureGeneric**
used in ArsdkListFlags.java
supposed to come from "com.parrot.drone.sdkcore.arsdk.ArsdkFeatureGeneric"

**ArsdkFeatureCamera**
used in "AnafiCameraRouter.java"
supposed to come from "om.parrot.drone.sdkcore.arsdk.ArsdkFeatureCamera".

The code cannot find them, and I cannot find them in any of the modules associated with groundsdkdemo project.

Any idea where they may be?

**Comment by mvinel** [comment]
Hi,

The 'groundsdk-android' git repository is only a part of the whole groundsdk workspace.
To build groundsdk, please follow the instructions [here](https://developer.parrot.com/docs/groundsdk-android/buildgroundsdk.html).

Regards.
